name: 'Organization Membership Request'
description: 'A request to become a Backstage organization member'
title: 'Org Member: <your-github-login>'
labels:
  - org-member-request
body:
  - type: markdown
    attributes:
      value: >
        ### Thank you for your interest and contributions to the Backstage project! ðŸ™

  - type: markdown
    attributes:
      value: >
        This form is used to request Organization Member status in the Backstage project,
        as described by the [Backstage Governance](https://github.com/backstage/community/blob/master/GOVERNANCE.md#organization-member).
        In addition to becoming member of the Backstage GitHub organization, this role also
        comes with the responsibilities and requirements that are described in the governance.

  - type: dropdown
    id: member-type
    validations:
      required: true
    attributes:
      label: 'Through which path are you seeking to become an organization member?'
      description: There are three different paths to becoming an organization member
      options:
        - 1. I been contributing for at least 3 months and wish to become a standalone org-member
        - 2. The team that I am a member of in my organization are maintainers of a Project Area in Backstage
        - 3. I am a maintainer of a plugin the Backstage Community Plugins Repository

  - type: textarea
    id: contributions
    attributes:
      label: '(1) Highlighted Contributions'
      description: 'This applies if you selected option 1 above. The Backstage governance requires that standalone organization members have made some contributions to the project. Please choose a couple (3-5) of these contributions that you would like to highlight. If you are the member of a Project Area Maintainer team, please let us know your organization, team, and project area instead.'
      placeholder: 'Link to GitHub issues, accepted PRs, or other contributions that you would like to highlight'

  - type: input
    id: project-area
    attributes:
      label: '(2) Project Area'
      description: 'This applies if you selected option 2 above. Please specify the project area that your team maintains'

  - type: input
    id: plugin-owner
    attributes:
      label: '(3) Plugin code owner PR'
      description: 'This applies if you selected option 3 above. Please link to the pull request where you were added as a code owner of a plugin in the community-plugins repository'

  - type: input
    id: discord-username
    attributes:
      label: 'What is your Discord username?'
      description: 'Let others know who you are in the Backstage community Discord'
      placeholder: 'DiscordUser#1234'

  - type: input
    id: organization
    attributes:
      label: 'What is the name of your current organization?'
      description: 'Let others know what organization you are a member of'
      placeholder: 'ACME Corp'

  - type: textarea
    id: other
    attributes:
      label: 'Any other context that you wish to share'

  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: 'Have you read the Code of Conduct?'
      options:
        - label: 'I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)'
          required: true
