name: '❓` Other'
description: 'Something not captured by any other template'
body:
  - type: markdown
    attributes:
      value: |
        This template can be used to create issues that don't fit any of the other templates. Valid examples include meta issues or other task tracking issues to help coordinate work, or informative issues that are kept around to appear in searches.

        Do not use this template to submit support or help requests, they will be closed. Please use other forums such as our [Community Discord](https://discord.gg/backstage-687207715902193673) instead.
  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Acknowledgement
      options:
        - label: I acknowledge that issues using this template may be closed without further explanation.
          required: true
  - type: textarea
    id: contents
    attributes:
      label: Comment
    validations:
      required: true
