name: Automate merge message
on:
  pull_request_target:
    branches: ['master']
    types: ['closed']

permissions:
  pull-requests: write
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  feedback:
    # prevent running towards forks, and only run on merged PRs
    if: github.repository == 'Rugvip/lerna-publish-experiment' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.merge_commit_sha }}'

      - name: fetch base
        run: git fetch --depth 1 origin ${{ github.event.pull_request.base.sha }}

        # We avoid using the in-source script since this workflow has elevated permissions that we don't want to expose
      - name: Generate Message
        id: generate-message
        run: |
          rm -f generate.js
          wget -O generate.js https://raw.githubusercontent.com/Rugvip/lerna-publish-experiment/master/scripts/generate-merge-message.js 1>&2
          node generate.js FETCH_HEAD > message.txt

      - name: Post Message
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
        with:
          script: |
            const owner = "Rugvip";
            const repo = "lerna-publish-experiment";
            const body = require('fs').readFileSync('message.txt', 'utf8').trim();
            const issue_number = Number(process.env.ISSUE_NUMBER);

            if (!body) {
              console.log(`skipping comment for #${issue_number}`);
              return;
            }

            console.log(`creating comment for #${issue_number}`);
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body,
            });
