name: Automate issue labels
on:
  issues:
    types:
      - labeled

jobs:
  stale:
    permissions:
      issues: write

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Remove needs:triage label
        uses: actions-ecosystem/action-remove-labels@v1
        if: >
          ${{ startsWith(github.event.label.name, 'priority:') || ( startsWith(github.event.label.name, 'needs:') && github.event.label.name != 'needs:triage' ) }}
        with:
          labels: needs:triage
