name: Issue
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: read # for github/issue-labeler to get repo contents
      issues: write # for github/issue-labeler to create or remove labels
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Add advanced issue labels
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
