name: Issue
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: read # for github/issue-labeler to get repo contents
      issues: write # for github/issue-labeler to create or remove labels
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Fetch common issue template
        id: fetch-template
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/ISSUE_TEMPLATE/.common.yaml',
              mediaType: {
                format: 'raw'
              }
            });
            require('fs').writeFileSync('.common.yaml', response.data);
            core.setOutput('template-path', '.common.yaml');

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: ${{ steps.fetch-template.outputs.template-path }}

      - name: Add advanced issue labels
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          token: ${{ secrets.GITHUB_TOKEN }}
