name: Master Build

on:
  workflow_dispatch:
    inputs:
      bool1:
        description: bool1
        required: false
        type: boolean
      bool2:
        description: bool2
        required: true
        default: false
        type: boolean
      bool3:
        description: bool3
        required: false
        default: false
        type: boolean
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: hmarr/debug-action@v2
    - name: bool1 A
      run: echo "Running from branch"
