name: Test PR
on:
  pull_request_target:
    branches: ['master']
    types: ['closed']

permissions:
  pull-requests: none
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  feedback:
    if: github.repository == 'Rugvip/lerna-publish-experiment'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.merge_commit_sha }}'

      - name: fetch base
        run: git fetch --depth 1 origin ${{ github.event.pull_request.base.sha }}

      - name: Say hi
        run: |
          echo "At 1"
          ls || echo "failed"
          cat hi.js || echo "failed"
          rm -f hi.js
          echo "At 2"
          ls || echo "failed"
          cat hi.js || echo "failed"
          wget -O hi.js https://raw.githubusercontent.com/Rugvip/lerna-publish-experiment/master/scripts/hi.js 1>&2
          echo "At 3"
          ls || echo "failed"
          cat hi.js || echo "failed"
          node hi.js
