name: Test

on:
  push:
    paths:
      - packages/**

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        derp: [a, b]
    name: "Test the thing ${{a}}"
    steps:
      - run: echo "Tested!"
